### ISSUE TITLE
Retrieve json files that are only abi format

### ISSUE THREAD

**Issue by galadd** [galadd/jags#7]
Presently, the program scans through all json files in the directory, and tries to process each. Files like package.json and package-lock.json gets retrieved. If you want to pick this issue, don’t do an `except` the package files, and there could be a possibility in the future where we have json files that are neither abi format nor package file

**Comment by Destiny-01** [comment]
Can this be assigned to me please

**Comment by galadd** [comment]
Check out CONTRIBUTING.md to see how to go about contributing to the repo
